opentofu/manifesto

- index.html
Excited to be working with everyone to develop such a critical component of cloud infrastructure in an open, community-driven, vendor-agnostic manner.
We plan to help with development and governance efforts.
> Massdriver pledge

- index.html
> Clarification on pledge

- index.html
Removed whatsapp and FB share buttons
Placed share buttons under Pledges title
Deleted poorly formed html tag
> Reordered sections

- style.css
Adding some breathing room on mobile. The main container goes 'full bleed' on small screens.
> Main container padding

- index.html
As co-founder and Chief Product Officer of Gruntwork, I can say that we are honored to participate in this manifesto. We believe in a solid, open foundation on which all infrastructure should be built and look forward to contributing to this effort.
> Add the Gruntwork pledge

- index.html
So there's a clear way for anyone to contact us, not just the press.
> Update contact info

- index.html
> Add Reddit and HN buttons

- index.html
- style.css
Included a common google font, added some basic typography styles, and a dark mode media query.
---
---
> A google font and some text styling

- index.html
> Fix HN url and description

- index.html
Removing md contribution details if we decide req'ing contribution details may alienate folks from supporting the initiative.
> Remove contribution details

- index.html
See the ["avoiding war"](https://gruntwork-io.slack.com/archives/C05MAK37AFQ/p1692036211930699) thread for context.
This is a different approach / request that we can consider. I'm not sure if this is actually better, so we should discuss, and pick whether we like this approach or the one that's live now.
> Switch focus to going back to truly open source, rather than a foundation

- index.html
Minor change in wording for better readability.
> minor grammar change

- index.html
Thanks for this initiative and we will be honored to belong and contribute to it.
> Add Finisterra to pledges

- index.html
Added two questions we frequently get along with anchors so we can link to them.
> Add FAQ, update date

- index.html
- style.css
This makes it easier to add yourself as an "individual":
Not sure if we want a "comments" column or not. Perhaps that would lead to too much spam / noise? I can remove if so.
> Move pledges to a table

- index.html
Add Cloud Posse to list of co-signers
> add cloud posse

- index.html
We like this initiative and would like to contribute
> Including Terrakube Project

- index.html
> add thschue to as individual contributor

- index.html
New PR following many changes after submitting PR https://github.com/opentffoundation/manifesto/pull/61
> Add Cirrus Assessment to pledges

- index.html
Adding Octo Ventures to the pledge.
> added Octo Ventures pledge

- index.html
Adding Kelvin Soares as an Individual.
> feat: adding kelvin soares

- index.html
> Add Alex Panayi Individual 

- index.html
> fix: adjusting kelvin soares table

- index.html
Add Mariano Rodríguez as Individual.
> Add MarianoRD

- index.html
> chore: add AutoCloud

- index.html
Amach agree with this manifesto and would like to support this effort.
> feat: Adding Amach

- index.html
The merge conflicts we're getting out of hand, and it's a bit cleaner if we consolidate companies, projects, and individuals into their own sections in the HTML.
This implements:
- https://github.com/opentffoundation/manifesto/pull/50
- https://github.com/opentffoundation/manifesto/pull/57
> Add Coherence, Add Nullstone, Consolidate companies, projects, and individuals

- index.html
- Adding our support from our team of infrastructure Developers!
> Add Support from RoseSecurity Research

- index.html
We at appCD (currently on stealth) support keeping Terraform open.
> Adds appCD

- index.html
Happy to add my own personal support as a engineer in what ever capacity is needed going fordward. I have more than 30yrs industry knowledge in developer and engineering and my current company is an AWS MSP that depend on TF and Spacelift
> Adding Technical Support

- index.html
I'm an SRE and goland progammer, and I've been using terraform for many years now.  It's an integral part of my workflow for managing cloud infrastructure, particularly AWS.  I've introduced it to multiple companies professionally, and I use it for maintaining personal infrastructure.
I was incredibly dismayed by Hashicorp adopting the BSL, and I was trying to figure out who to reach out to about a possible fork.  Thank you for organizing this and making a big public stand.  I will be using OpenTF for future upgrades to my tooling both personally and professionally, and I hope to be able to contribute to ongoing development efforts.
> Jeff Frasca sign OpenTF manifesto as individual

- index.html
Signed the manifesto
I'm a devops engineer and have been using terraform for the last 6 years, primarily using the open source cli version within a jenkins or github actions job. Recently I've been lucky enough to use Spacelift to automate the orchestration of Terraform.
I'm very disappointed to see Hashicorp block their competitors through the unexpected BSL license change. If your product isn't good enough to compete with your competitors then step up your game Hashicorp!
> Add Individual: Jeff Wenzbauer

- index.html
signed the manifesto
I'm a backend engineer that uses terraform into my day-to-day and makes my life easier.
> Add individual: Kevin Rathbun

- index.html
I am a cloud and platform architect and developer who uses TF to provision cloud and on-premise infrastructure and configurations. I maintain private providers and internal forks.
> Added Individual: Daniel Ristic

- index.html
> Remove duplicate

- index.html
Adding Indeo Solutions company
> Adding Indeo Solutions company

- index.html
> Adding Coin Graham IV

- index.html
https://spdx.org/licenses/BUSL-1.1.html
> fix: spdx identifier for BUSL

- README.md
- index.html
Reverts opentffoundation/manifesto#139
> Revert "style: HTML and language"

- index.html
Fully support The OpenTF Manifesto! Keeping Terraform open source is crucial for a thriving community. Let's ensure its future remains open and inclusive.💪
> pledge: add Lawal AbdulLateef

- index.html
> Add Hestio company

- index.html
Signing OpenTF manifesto, adding Aymen Segni as an Individual
> Add Aymen Segni as Individual

- index.html
> Add lgallard as individual

- index.html
We will sign this manifest. Please merge this.
> add elastic2ls

- index.html
Thank you for starting this initiative. I would like to pledge my support to the efforts of OpenTF.
> Pledge support

- index.html
Add Labyrinth Labs as a supporter.
> Add Labyrinth Labs

- index.html
Add AlexTorres as a supporter, as individual.
> feat: add alex-torres as oss contributor

- index.html
Added Zerodha Tech to the list of supporter companies.
> feat: added Zerodha Tech to the list of supporter companies.

- index.html
TF is important and crucial to many teams these days, it's important to keep it open source.
> Support for OpenTF

- index.html
works as a full time developer for env0
and would like to individually support this effort
> Add as a Individual contributor

- index.html
> Add my pledge to table

- index.html
Adding my details to the pledge table
> Update index.html - add KenSpur

- index.html
> Update index.html - Add pdefreitas

- index.html
Added Cloudresty and fixed whitespace
> Added Cloudresty and fixed whitespace

- index.html
> Add kneekeel

- index.html
> Adding Individual and Company: Carlos Manuel Soares and CMPSoares Lda.

- index.html
The heading about "supporters" and instructions on how to add yourself should be right next to the table itself.
> Move headings

- index.html
> Add KaiKorla

- index.html
> Add Luis Gonzalez

- index.html
As someone who's promoted Terraform's use in the past both internally at organizations, and externally via my writing and tutorials, I would like my name added to this list. I will no longer promote Terraform unless and until its license becomes truly open source again.
> Add geerlingguy to list

- index.html
> Add Arturo Delgado

- index.html
Adding my Signature to the manifesto. Thanks!
> Add signature to manifesto

- index.html
> Add Dan Piet to cause

- index.html
> sign manifesto

- index.html
> Add Ervin Szilagyi's pledge

- index.html
I agree to the Manifesto and request to add my name
> add Seonbo Shim

- index.html
Hashicorp, please reconsider getting back the previous license.
> add ABacao to the cause

- index.html
I support the opentf manifesto and will support the open-source community efforts to the best that I can
> added keivinonline

- index.html
> Update index.html - Adding myself

- index.html
Adding myself to the initiative - Terraform is vital to my career's well-being.
> Add Adrian Otrębski to manifesto

- index.html
> Add Steven B.

- index.html
This adds Justin Smith as a contributor to OpenTF Foundation.
> Add Justin Smith as contributor

- index.html
Add David Hill as a supporter to OpenTF foundation
> Add David Hill as signatory

- index.html
Add Ajinkya Bhabal as a supporter to OpenTF foundation
> Add Ajinkya Bhabal as signatory

- index.html
Add Robin Gruyters as a supporter to OpenTF foundation
> chore: add Robin as supporter

- index.html
> Add Argo DevOps

- count.js
- index.html
- style.css
https://github.com/opentffoundation/manifesto/issues/385
> Added counter for Companies, Projects and Individuals

- index.html
> Added individual: Eric Vallee

- index.html
> Amend typo on closing tag

- index.html
Hi, 
I support the OpenTF project to maintain a version of Terraform that is truly open-source.
> Adding QJOLY(me)  - Testing, CICD, Documentation

- index.html
Hey folks, support your move and signing this manifesto.
> It does matter for me

- index.html
I'll help however I can, but I'm probably most useful on the website side and just general organisational administration tasks.
> Add myself to index.html

- index.html
> [Sign] Miguel Zenteno

- index.html
Added initializ.io Company support
> Added initializ.io Company support

- index.html
> joining the manifesto

- index.html
Pledging my allegiance to the cause.
> Sign: 4s3ti

- index.html
Willing to contribute in testing, development, adoption and other open-source community efforts
> Add contributor - sansmoraxz

- index.html
Add Szymon Kodrębski as signer
> Add Szymon Kodrębski as signer

- index.html
> add Sergio Saiz

- index.html
Sign @pkutishch as an individual to contribute to https://github.com/opentffoundation's efforts in having Terraform Open-Source.
> Adding individual pavlo kutishchev

- index.html
Sign @ashwin2125 as an individual to contribute to @opentffoundation's efforts in having Terraform Open-Source.
> Signature - Add Individual - Ashwin Gopalsamy

- index.html
> Add Noam & Hakan to index.html

- index.html
Happy to join this and I hope it makes a difference for the future of Terraform 💯
> feat: adds Masterpoint to the list of signed companies

- index.html
> DEVOPS-00: Sign

- index.html
> Update index.html with my support

- index.html
Added Rogerio Fonseca as individual contributor
> Added Rogerio Fonseca as individual contributor

- index.html
> Add my support!

- index.html
> Sign the manifesto

- index.html
This PR fixes a few syntax issues, nothing serious.
> Fix a few HTML issues

- index.html
Added Dmitry Kisler's contribution pledge.
To maintain terraform as FOSS.
> add kislerdm to contributors pledge

- index.html
> Add Marcos Oliveira Junior to manifesto pledge

- index.html
> Adding Trevor Case to manifesto pledge

- index.html
Signing manifesto by Daniel Sanchez
> Signing manifesto

- index.html
> add Infraspec

- index.html
Sign manifesto to support OpenTF
Cheers,
Danh Huynh
Director of DevOps at Panzura
> Sign manifesto to support OpenTF

- index.html
> feat: add my manifesto

- index.html
I will be glad to help. I am the maintainer of the official [OpenVPN Terraform Provider](https://github.com/openVPN/terraform-provider-openvpn-cloud/).
Company ANNA Money is an active user of Terraform.
> Added Denis Arslanbekov & ANNA Money company

- index.html
Thanks for creating this initiative!
> add: Krasimir Koeff to opentf manifesto

- index.html
> Add Goran Vasic to manifesto pledge

- index.html
I support OpenTF as an open-source contributor
> Signing the manifesto

- index.html
> fix:added my manifesto

- index.html
> feat: added Cyrus Li pledge

- index.html
Terraform deserves to continue to be FOSS. Thank you
> [Pledge] Add MNThomson to contributors pledge

- index.html
Add Bogdan Naydenov to Manifesto pledge
> Add Bogdan Naydenov to Manifesto pledge

- index.html
Adding myself to the manifesto
> Add Yulian Kuncheff to manifesto

- index.html
> Add David Hay to Manifesto pledge

- index.html
> feat: adds Veronika Gnilitska

- index.html
Added some example PRs that show that Hashi hasn't accepted community contributions that conflict with their commercial products.
> Add arguments to FAQ

- index.html
Hi all, 
Thanks for your hard work in this effort. I am committing personal time to be part of this community and future development.
> Manifest signing: Bart van der Braak as co-signee

- index.html
chore: sign manifesto by Marcio Junior Vieira, CEO at Ambiente Livre Company - Brazil.
Open Source company in Brazil: https://www.ambientelivre.com.br
> sign Manivest Company - Ambiente Livre

- index.html
There are some small problems in the format of the name, I fix it, please review, thanks.
> fix:name format

- index.html
Let's rebuild the opentf ecosystem!
> Sign manifesto - Yao Lu

- index.html
Let's come together and build an open platform for Terraform. 
Signing personally and on behalf of my company.
> commitment and pledge for opentf

- index.html
Add correct URL im Ambiente Livre
> Ambiente Livre - Company

- index.html
- Signing manifesto Edgar Daniel Acosta Jaimes.
> signing manifesto edgar acosta

- index.html
> Sign manifesto - Jyotirmoy Bandyoapadhayaya

- index.html
- style.css
Just made the link SVGs white when the page is in dark mode.
> Made link SVGs more visible in dark mode.

- index.html
Added my self as a contributer.
I am working as a terraform provider developer. I have good experience on Terraform and Golang
> Added contributer ravi prakash bharti

- index.html
> Add announcement date

- index.html
> Sign Manifesto 

- index.html
replaced 'www.' with 'https://' on my link and the guy above so href works correctly
> Fixed href link for myself and guy above

- index.html
I have added consistent formatting for the HTML and removed the duplicate entry for Nebari.dev
> Cleanup and Formatting

- index.html
I can also help in case OpenTF moves to a Decentralized Autonomous Organization (DAO) structure that's popular in the Web3 space which would help prevent a single organization from making actions without the community's consent.
> Add pledge to OpenTF Manifesto

- index.html
Signed by: @sombochea
Type: Individual
References: Education; System Administrator; Testing; Development; open-source community efforts
> Add sombochea signed to OpenTF Manifesto

- count.js
- index.html
Hi, I noticed that there is a foundation in the co-signers section, but there is no counter for that, so I added it!
> Add foundation counter

- index.html
Hey 👋 
My signature, you approve. Let's bake.
> add Igal Klebanov signature.

- index.html
> jackishere signature

- index.html
> rawis signing opentf manifesto

- index.html
Thank you to the OpenTF team for your efforts. Adding my name under Co-Signed.
> Add Jim Diroff II as Co-Signed

- index.html
> Adds bealesh/David Beale

- index.html
> Adding a New Individual

- index.html
To better inform the readers about what the changes are!
> Add a link to Hashicorp's FAQ

- index.html
good luck, you have my support!
> feat: append my name

- index.html
Supporting this Great Initiative!
> Signed the Manifesto

- index.html
Good luck everybody! I believe in this cause
> add jakob kubicki

- index.html
> feat: sign manifesto

- index.html
Let me know if you need anything else. Happy to help with software development efforts, currently using TF for a number of different deployments and fairly knowledgeable about Cloud ecosystems.
> Daniel Wasserlauf Signed Manifesto

- index.html
> Sign Alex Caesar

- index.html
Recube Sign the OpenTF manifesto
> Recube Sign the OpenTF manifesto 

- index.html
> Signing off manifesto

- index.html
Signed manifesto, 
Noticed a duplicate row so removed the extra one
> Sign Manifesto, remove diplicate row

- index.html
Added self - Ron DeMena to contributors
!!! Open Source TF !!!
Signed-off-by: Ron DeMena <ron@demena.net>
> Added self - Ron DeMena to contributors

- index.html
> Update index.html, Add name to list

- index.html
We have an abundance of cloud credits that we are happy to share for any add'l compute that we need.
> adding a pledge for cloud compute (AWS, GCP, or Azure)

- index.html
Fixing what appears to be a bad merge here: https://github.com/opentffoundation/manifesto/pull/1031.
> Fix bad merge

- index.html
> Add pledge

- index.html
> OpenTofu Pledge

- index.html
Removed duplicate entry of my name, it already exists at line 1869
Integrity
> Remove duplicate entry

- index.html
Adding in my name for additional support.
> Sign the pledge

- index.html
[DevRev](https://devrev.ai/), as users of Terraform Cloud and CNCF technologies, would like to add our support for the open-source ideals in the OpenTofu manifesto.
Thanks,
[Nghia](https://www.linkedin.com/in/n-h-nguyen/)
> enh: devrev company manifesto support

- index.html
Signed OpenTofu Manifesto! :-)
> Signed Manifesto

- index.html
The project turned into wrong direction so I'm withdrawing the signature.
> Withdraw the signature

- index.html
We are pleased to support 1 full-time employee for the OpenTofu core team. Hopefully more to come!
> Update Gruntwork's OpenTofu commitment!
